import type { ScriptDefinition } from '../script-types';

/** HSK-style starter set: common simplified characters + pinyin scaffold. */
const ZH_ALPHABET_ENTRIES = [
  { letter: '一', latinHint: 'yī' },
  { letter: '二', latinHint: 'èr' },
  { letter: '三', latinHint: 'sān' },
  { letter: '人', latinHint: 'rén' },
  { letter: '入', latinHint: 'rù' },
  { letter: '大', latinHint: 'dà' },
  { letter: '天', latinHint: 'tiān' },
  { letter: '小', latinHint: 'xiǎo' },
  { letter: '山', latinHint: 'shān' },
  { letter: '水', latinHint: 'shuǐ' },
  { letter: '火', latinHint: 'huǒ' },
  { letter: '木', latinHint: 'mù' },
  { letter: '日', latinHint: 'rì' },
  { letter: '月', latinHint: 'yuè' },
  { letter: '目', latinHint: 'mù' },
  { letter: '土', latinHint: 'tǔ' },
  { letter: '士', latinHint: 'shì' },
  { letter: '干', latinHint: 'gān' },
  { letter: '千', latinHint: 'qiān' },
  { letter: '十', latinHint: 'shí' },
  { letter: '口', latinHint: 'kǒu' },
  { letter: '手', latinHint: 'shǒu' },
  { letter: '我', latinHint: 'wǒ' },
  { letter: '你', latinHint: 'nǐ' },
  { letter: '好', latinHint: 'hǎo' },
  { letter: '学', latinHint: 'xué' },
  { letter: '生', latinHint: 'shēng' },
  { letter: '中', latinHint: 'zhōng' },
  { letter: '国', latinHint: 'guó' },
  { letter: '上', latinHint: 'shàng' },
  { letter: '下', latinHint: 'xià' },
  { letter: '门', latinHint: 'mén' },
  { letter: '车', latinHint: 'chē' },
  { letter: '东', latinHint: 'dōng' },
  { letter: '西', latinHint: 'xī' },
  { letter: '男', latinHint: 'nán' },
  { letter: '女', latinHint: 'nǚ' },
  { letter: '开', latinHint: 'kāi' },
  { letter: '关', latinHint: 'guān' },
  { letter: '多', latinHint: 'duō' },
  { letter: '少', latinHint: 'shǎo' },
] as const;

export const ZH_SCRIPT: ScriptDefinition = {
  id: 'zh',
  name: 'Chinese (Simplified)',
  nativeLabel: '中文',
  tagline: 'Decode characters you see around you — not a full course.',
  overviewTitle: 'Starter character set',
  overviewSubtitle:
    'Common simplified characters with pinyin hints. Hints fade in practice.',
  matchPrompt: 'Tap the character that matches the pinyin hint.',
  alphabet: ZH_ALPHABET_ENTRIES,
  confusablePairs: [
    { id: 'ren-ru', glyphs: ['人', '入'], latinHints: ['rén', 'rù'] },
    { id: 'tu-shi', glyphs: ['土', '士'], latinHints: ['tǔ', 'shì'] },
    { id: 'gan-qian', glyphs: ['干', '千'], latinHints: ['gān', 'qiān'] },
    { id: 'ri-mu', glyphs: ['日', '目'], latinHints: ['rì', 'mù'] },
  ],
};
